import unittest

import ../src/day17

const testInput = """
x=495, y=2..7
y=7, x=495..501
x=501, y=3..7
x=498, y=2..4
x=506, y=1..2
x=498, y=10..13
x=504, y=10..13
y=13, x=498..504
"""

suite "Day 17 Tests":
  test "Can parse and draw a grid":
    const expected = """
........+.........
..............#...
...#..#.......#...
...#..#..#........
...#..#..#........
...#.....#........
...#.....#........
...#######........
..................
..................
......#.....#.....
......#.....#.....
......#.....#.....
......#######.....
..................
..................
..................
"""
    var grid = newGrid((500, 0), parseInput(testInput))
    check $grid == expected

  test "Can drop the water":
    const expected = """
........+.........
........|.....#...
...#..#||||...#...
...#..#~~#|.......
...#..#~~#|.......
...#~~~~~#|.......
...#~~~~~#|.......
...#######|.......
..........|.......
.....|||||||||....
.....|#~~~~~#|....
.....|#~~~~~#|....
.....|#~~~~~#|....
.....|#######|....
..................
..................
..................
"""
    var grid = newGrid((500, 0), parseInput(testInput))
    grid.dropWater()
    check $grid == expected

  test "Can count the water amounts":
    var grid = newgrid((500, 0), parseInput(testInput))
    grid.dropWater()
    check:
      grid.countWater() == 57
      grid.countWater({ RestingWater }) == 29
